apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: {{ .Values.namespace }}
  labels:
    app: user-platform
    component: config
data:
  LOGIN_TITLE: {{ .Values.uiConfig.LOGIN_TITLE | quote }}
  REGISTER_TITLE: {{ .Values.uiConfig.REGISTER_TITLE | quote }}
  WELCOME_MESSAGE: {{ .Values.uiConfig.WELCOME_MESSAGE | quote }}
